[build]
  # 빌드 명령어 (정적 사이트이므로 필요 없음)
  command = ""
  # 배포할 디렉토리
  publish = "."
  # 함수 디렉토리
  functions = "netlify/functions"

# 개발 환경 설정
[dev]
  command = "python -m http.server"
  port = 8888
  targetPort = 8000
  publish = "."
  autoLaunch = true

# 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# 환경 변수 설정 예시 (실제 값은 Netlify 대시보드에서 설정)
[context.production.environment]
  # 이 값들은 실제로 사용되지 않으며, Netlify 대시보드에서 설정해야 함
  SUPABASE_URL = "실제 값은 Netlify 대시보드에서 설정하세요"
  SUPABASE_KEY = "실제 값은 Netlify 대시보드에서 설정하세요"
  ADMIN_PASSWORD = "실제 값은 Netlify 대시보드에서 설정하세요"
